apiVersion: v1
kind: ConfigMap
metadata:
  name: registry
data:
  config.yml: |
    version: 0.1
    http:
        addr: :5000
        tls:
            certificate: /var/run/secrets/certs/tls.crt
            key: /var/run/secrets/certs/tls.key
    storage:
        s3:
            accesskey: asdf
            secretkey: qwertyuiop
            region: us-east-1
            regionendpoint: http://10.0.0.10:9000
            bucket: registry
            encrypt: false
            secure: false
            v4auth: true
            chunksize: 5242880
            rootdirectory: /
